CREATE TABLE IF NOT EXISTS SOCIO(
    NIF CHAR(9) UNIQUE PRIMARY KEY,
    Nombre VARCHAR(30) NOT NULL,
    Apellidos VARCHAR(120) NOT NULL,
    Direccion VARCHAR(255) NOT NULL,
    Telefono CHAR(9) UNIQUE NOT NULL,
    Fecha_nac DATE NOT NULL,
    Fecha_alta DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS TEMA(
    Cod_tema INT(4) AUTO_INCREMENT PRIMARY KEY,
    Nombre_tema VARCHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS PAIS(
    Nombre VARCHAR(120) NOT NULL UNIQUE,
    Cod_pais INT(3) UNIQUE NOT NULL PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS AUTOR(
    Cod_autor INT(4) PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(30) NOT NULL,
    Apellidos VARCHAR(120) NOT NULL,
    Pais VARCHAR(120) NOT NULL,
    FOREIGN KEY (Pais) REFERENCES PAIS (Nombre)
);
CREATE TABLE IF NOT EXISTS EDITORIAL(
    Cod_editorial INT(4) PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(60) NOT NULL,
    Direccion VARCHAR(255) NOT NULL,
    Pais VARCHAR(120) NOT NULL,
    FOREIGN KEY (Pais) REFERENCES PAIS (Nombre)
);
CREATE TABLE IF NOT EXISTS LIBRO(
    Cod_libro INT(6) PRIMARY KEY AUTO_INCREMENT,
    Titulo VARCHAR(120) NOT NULL,
    Año_publi date,
    Tema INT(4) NOT NULL,
    autor INT(4) NOT NULL,
    editorial INT(4) NOT NULL,
    FOREIGN KEY (Tema) REFERENCES TEMA(Cod_tema),
    FOREIGN KEY (autor) REFERENCES AUTOR(Cod_autor),
    FOREIGN KEY (editorial) REFERENCES EDITORIAL(Cod_editorial)
);
CREATE TABLE IF NOT EXISTS EJEMPLAR(
    ISBN CHAR(14) UNIQUE PRIMARY KEY,
    Libro INT(6) AUTO_INCREMENT,
    FOREIGN KEY (Libro) REFERENCES LIBRO (Cod_libro)
);
CREATE TABLE IF NOT EXISTS SOCEJEM(
    socio CHAR(9) PRIMARY KEY,
    ISBN CHAR(14) NOT NULL,
    fecha_pres date,
    FOREIGN KEY (socio) REFERENCES SOCIO (NIF),
    FOREIGN KEY (ISBN) REFERENCES EJEMPLAR (ISBN)
);
CREATE TABLE IF NOT EXISTS LIBTEM(
    Cod_libro INT(6) PRIMARY KEY,
    Cod_tema INT(4) AUTO_INCREMENT NOT NULL,
    FOREIGN KEY (Cod_libro) REFERENCES LIBRO (Cod_libro),
    FOREIGN KEY (Cod_tema) REFERENCES TEMA (Cod_tema)
);